<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Company>Evotec</Company>
        <Authors>Przemyslaw Klys</Authors>
        <VersionPrefix>1.0.0</VersionPrefix>
        <AssemblyName>PowerBGInfo</AssemblyName>
        <Copyright>(c) 2011 - 2025 Przemyslaw Klys @ Evotec. All rights reserved.</Copyright>
        <TargetFrameworks>net472;net8.0-windows;net9.0-windows</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>Latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <UseSystemDrawing>true</UseSystemDrawing>
    </PropertyGroup>
    <PropertyGroup Condition="'$(PublishAot)' == 'true'">
        <TargetFrameworks>net8.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DesktopManager" Version="3.6.1" />
        <PackageReference Include="ImagePlayground.Gdi" Version="2.0.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(ChartForgeXProjectPath)' != ''">
        <ProjectReference Include="$(ChartForgeXProjectPath)" />
    </ItemGroup>
    <ItemGroup Condition="'$(ChartForgeXProjectPath)' == ''">
        <PackageReference Include="ChartForgeX" Version="0.1.0" />
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>PowerBGInfo.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' != 'net472'">
        <PackageReference Include="System.Management" Version="8.0.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
        <Reference Include="System.Management" />
        <Reference Include="System.Web.Extensions" />
    </ItemGroup>
</Project>
